ALTER TABLE "permissions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "role_permissions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "roles" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "users" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "authors" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "book_categories" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "book_category_links" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "book_editions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "books" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "sources" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "quran_surahs" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "quran_verses" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "tafsir_entries" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "tafsir_sources" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "translations" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "verse_translations" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "quran_reciters" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "quran_verse_audio" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "hadith_books" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "hadith_collections" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "hadith_grades" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "hadith_topic_links" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "hadith_topics" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "hadith_translations" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "hadiths" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "fiqh_divergence_notes" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "fiqh_positions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "fiqh_suggestions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "fiqh_topics" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "schools" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "scholar_books" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "scholar_schools" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "scholars" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "event_sources" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "historical_events" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "historical_periods" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "scholar_events" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "concept_divergences" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "concept_relations" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "concepts" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "learning_lessons" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "learning_paths" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "learning_quiz_options" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "learning_quiz_questions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "user_progress" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "bookmarks" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "collection_items" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "collections" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "notes" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "audit_logs" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "report_history" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "reports" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "prophets" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "ai_embeddings" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "dua_categories" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "duas" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "push_subscriptions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "reading_rotation_settings" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "reminders" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "auth_tokens" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "user_streaks" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "streak_alert_settings" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "dua_schedule_settings" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "prayer_alert_settings" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "user_achievements" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "user_daily_actions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "user_gamification" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "user_stats" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "marketing_group_members" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "marketing_groups" ENABLE ROW LEVEL SECURITY;