import {
  AlarmClock,
  Baby,
  BedDouble,
  BookOpen,
  CloudLightning,
  Coins,
  Droplet,
  Flame,
  Frown,
  GraduationCap,
  Heart,
  HeartCrack,
  HeartHandshake,
  HelpCircle,
  Home,
  Landmark,
  LifeBuoy,
  MessageCircle,
  Moon,
  MoonStar,
  PawPrint,
  Plane,
  RotateCcw,
  Shirt,
  ShieldCheck,
  ShoppingBag,
  Smile,
  Sparkles,
  Stethoscope,
  Sunrise,
  Sunset,
  UtensilsCrossed,
  Volume2,
  type LucideIcon,
} from "lucide-react";

/** Icone illustrative par categorie (purement decorative, sans donnee associee en base). */
export const DUA_CATEGORY_ICONS: Record<string, LucideIcon> = {
  matin: Sunrise,
  soir: Sunset,
  "apres-la-priere": Sparkles,
  "avant-de-dormir": Moon,
  "au-reveil": AlarmClock,
  repas: UtensilsCrossed,
  toilettes: Droplet,
  maison: Home,
  voyage: Plane,
  "detresse-et-anxiete": LifeBuoy,
  "apres-adhan": Volume2,
  salawat: Sparkles,
  protection: ShieldCheck,
  "visite-malade": Stethoscope,
  mariage: Heart,
  colere: Flame,
  marche: ShoppingBag,
  "phenomenes-naturels": CloudLightning,
  "nouvelle-lune": MoonStar,
  eternuement: MessageCircle,
  ramadan: MoonStar,
  parents: HeartHandshake,
  enfants: Baby,
  tristesse: HeartCrack,
  bonheur: Smile,
  doute: HelpCircle,
  repentir: RotateCcw,
  richesse: Coins,
  "hajj-umra": Landmark,
  louange: Sparkles,
  priere: BookOpen,
  societe: HeartHandshake,
  tentation: Flame,
  connaissance: GraduationCap,
  nuit: BedDouble,
  deces: Frown,
  mosquee: Landmark,
  vetements: Shirt,
  ablutions: Droplet,
  animaux: PawPrint,
  maladie: Stethoscope,
  "40-rabbana": BookOpen,
};

export function getDuaCategoryIcon(slug: string): LucideIcon {
  return DUA_CATEGORY_ICONS[slug] ?? HelpCircle;
}
